### ISSUE TITLE
Unable to find .exe

### ISSUE THREAD

**Issue by goose-can** [Mpstark/BattleTechModLoader#12]
Forgive my lack of tech savvy.  After extracting to the \BATTLETECH\BattleTech_Data\Managed\ I'm not seeing the ...Injector.exe.  I tried renaming BattleTechModLoaderInjector.csproj to BattletechModLoaderInjector.exe but it wouldn't run.  Searched BATTLETECH\*.* no luck.  Help.  Thanks

**Comment by Mpstark** [comment]
You need to download a release from here: https://github.com/Mpstark/BattleTechModLoader/releases

You're downloading the source.
