### ISSUE TITLE
No BTMLinjector exe

### ISSUE THREAD

**Issue by Katzenhai** [Mpstark/BattleTechModLoader#15]
I'm unsure if this is an issue with Win 10 or not but I've read through the instructions several times and I cannot find the .exe to run. Knowing me it's probably something I did wrong but hopefully someone can clear this up for me.

**Comment by Mpstark** [comment]
Download a release from [this page](https://github.com/Mpstark/BattleTechModLoader/releases).

**Comment by Katzenhai** [comment]
Thank you! (just got home from work) I appreciate the answer~
