### ISSUE TITLE
GOG patch 1.03-1.04 fails - error writing to Assembly-CSharp.dll

### ISSUE THREAD

**Issue by adamanden** [Mpstark/BattleTechModLoader#19]
As the title says, the GOG patch returned an error during the patching process. 

The log reports :
Error modifying:    C:\InstalledGames\BATTLETECH\BattleTech_Data\Managed\Assembly-CSharp.dll

I had a backup of Assembly-CSharp.dll prior to BTML injection. Upon restoring this and running the patcher again, I get a bunch of errors in the log (essentially everything except Assembly-CSharp.dll is throwing an error)

It seems that the GOG patcher does not roll back in case of an error during the patching process, resulting in a mix of patched and unpatched files. I understand that this is an issue with the GOG patcher (since apparently Steam just overwrites the pertinent files regardless if they have been modified or not) and not BTML itself. However, to avoid this issue in the future perhaps it would be good to include a warning or some instructions to backup Assembly-CSharp.dll prior to BTML injection, then to restore this backup prior to patching a new version of the game in the case of a GOG-based install.

**Comment by jerichodrumm** [comment]
Tried this today 4/31/18
\Managed\Assembly-CSharp.dll was created.  No errors.  However entering the game itself "/W MODTEK"  not displayed.   Double checked each mech in skirmish. NO changes loaded from MOD.  "JK-Variants"
Nothing seen of "UnseenMechs_UsingExistingModels" either.  
Hope this helps in someway

**Comment by Mpstark** [comment]
I've never had any problems with GOG Galaxy patching the game at all. I don't feel as if there is anything that I can do to correct this issue.
