### ISSUE TITLE
BattleTechModLoaderInjector.exe NOT FOUND

### ISSUE THREAD

**Issue by ret7army** [Mpstark/BattleTechModLoader#23]
Attempted to download the zip, but did not get the exe file

**Comment by Mpstark** [comment]
You need to download a release, not the source code. https://github.com/Mpstark/BattleTechModLoader/releases

https://github.com/Mpstark/ModTek/wiki/The-Drop-Dead-Simple-Guide-to-Installing-BTML-&-ModTek-&-ModTek-mods
