### ISSUE TITLE
OSX: BTML search path for Mods folder broken

### ISSUE THREAD

**Issue by ffaristocrat** [Mpstark/BattleTechModLoader#8]
Backslash isn't used for directory navigation on OSX. As a result, BTML creates & uses a folder literally named `..\..\..\Mods`.

It needs to navigate the directory structure in an OS agnostic way.

**Comment by schreiaj** [comment]
https://github.com/Mpstark/BattleTechModLoader/blob/master/BattleTechModLoader/BTModLoader.cs#L111

Needs to look like `Path.GetFullPath(Path.Combine({manifestDirectory, "..", "..", "..", "Mods"})`

(I'm not much in the way of a C# dev, I'll take some time to figure out how to build it myself sometime this weekend)

**Comment by ffaristocrat** [comment]
For whatever reason, my(or BT's?) version of .NET doesn't have a version of Path.Combine that can simply take a list. Hence the more hacky nested version in my PR.

**Comment by Mpstark** [comment]
Merged pull request.
